#!groovy

pipeline {

  agent any

  parameters {
    string(
      name: 'GIT_BRANCHES_GALAXY',
      defaultValue: '*/master',
      description: "Git branch or tag name or commit id to retrieve of GIT_URL to retrieve Ansible galaxy requirement file"
    )
    string(
      name: 'GIT_URL',
      defaultValue: '',
      description: "GitHub URL to retrieve Ansible galaxy requrements file"
    )
    string(
      name: 'REQUIREMENTS_FILE',
      defaultValue: '',
      description: "Ansible Galaxy requirement file"
    )
    string(
      name: 'WORKING_DIR',
      defaultValue: 'git-repo',
      description: 'Job working directory'
    )
  }

  stages {
    stage('Retrieve Ansible galaxy requirement file from Github') {
      steps {
        checkout(
          [
            $class: 'GitSCM',
            branches: [
              [
                name: "${params.GIT_BRANCHES_GALAXY}"
              ]
            ],
            extensions: [
              [
                $class: 'RelativeTargetDirectory',
                relativeTargetDir: "${params.WORKING_DIR}"
              ]
            ],
            doGenerateSubmoduleConfigurations: false,
            submoduleCfg: [],
            userRemoteConfigs: [
              [
                url: "${params.GIT_URL}"
              ]
            ]
          ]
        )
      }
    }

    stage('Execute ansible-galaxy command') {
      steps {
        dir ("${params.WORKING_DIR}") {
          sh "ansible-galaxy install -r ${params.REQUIREMENTS_FILE}"
        }
      }
    }
  }
}
